### ISSUE TITLE
Cannot MOV the Task Manager window

### ISSUE THREAD

**Issue by RevealedFrom** [ritchielawrence/cmdow#22]
I am able to move every visible window except the Task Manager (taskmgr).

I am able to `/ACT` it, confirming that I have correct handle. However, no amount of `/MOV` will move it.

Is there something special about the Task Manager application?

PS: Thanks for the great piece of work. I find this very handy to reposition all my >30 applications on my Extended Desktop whenever my 4K display is powered up a bit behind my laptop coming out of hibernation and all the windows fall into my laptop's display. I make a snap shot of all the windows coordinates regularly, and have another script to reposition from the saved snapshot.

**Comment by SamHasler** [comment]
Task manager runs elevated. You should be able to MOV it from an elevated
command prompt.
ᐧ
