### ISSUE TITLE
Potentially Unwanted Software

### ISSUE THREAD

**Issue by RevealedFrom** [ritchielawrence/cmdow#23]
My Windows 10 is now flagging cmdow as follows:

![image](https://user-images.githubusercontent.com/5305957/88193750-9cf61d80-cc70-11ea-89e8-abe1d5a005aa.png)

Is it ok to allow it?

**Comment by ritchielawrence** [comment]
Please see https://github.com/ritchielawrence/cmdow#is-cmdow-malware
