### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by SamHasler** [ritchielawrence/cmdow#4]
Currently you can only filter by taskbar or window name (Caption). It would be useful to be able to filter by other criteria such as:

* Image name
* Window Status
   * Visibility: Visible or Hidden
   * Minimized, Maximized, Restored,
   * Active, Inactive
   * Enabled, Disabled
* Level - i.e. filter to top level windows.
*  Size
   * Has size (width/height not 0)
   * width / height is =/>/<
* position?

**Comment by ritchielawrence** [comment]
Hi SamHasler,

This might be implemented. In the meantime, you could use FINDSTR and a FOR loop to filter on everything you suggested. Here's some examples:-

```batch
rem filter level 4 windows
cmdow | findstr /r /c:"^[^ ]*[ ]4"

rem filter maximised windows
cmdow | findstr /r /c:"^[^ ]*[ ][^ ]*[ ][^ ]*[ ]Max"

rem filter active window
cmdow | findstr /r /c:"^[^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ]Act"

rem filter disabled windows
cmdow | findstr /r /c:"^[^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ]Dis"

rem filter visible windows
cmdow | findstr /r /c:"^[^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ][^]*[ ]Vis"

rem filter explorer.exe windows
cmdow | findstr /r /c:"^[^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ][^ ]*[ ][^]*[ ][^ ]*[ ]explorer"

rem filter level 4 windows
for /f "tokens=1-8*" %%a in ('cmdow') do (
  if "%%b" EQU "4" echo %%a %%b %%c %%d %%e %%f %%g %%h %%i
)

rem filter visible level 2 windows
for /f "tokens=1-8*" %%a in ('cmdow') do (
  if "%%b" EQU "2" if "%%g" EQU "Vis" echo %%a %%b %%c %%d %%e %%f %%g %%h %%i
)

rem filter visible windows wider than 1000
for /f "tokens=1-12*" %%a in ('cmdow /p') do (
  if "%%g" EQU "Vis" if %%j GTR 1000 echo %%a %%b %%c %%d %%e %%f %%g %%h %%i %%j %%k %%l %%m
)
```

**Comment by SamHasler** [comment]
Wow, thanks for taking the time to write that up!

**Comment by SamHasler** [comment]
Perhaps you could add these examples to the documentation.

**Comment by ritchielawrence** [comment]
Already done :)
[https://ritchielawrence.github.io/cmdow/#faqs](https://ritchielawrence.github.io/cmdow/#faqs)
