### ISSUE TITLE
Selecting a Window Based on Image

### ISSUE THREAD

**Issue by ThunderSniper** [ritchielawrence/cmdow#5]
Is the above possible? If I have two windows open both named "CRAZY WINDOW NAME" one being a program/executable and another being "explorer", is it possible to just target the explorer window and leave the program/executable alone?

**Comment by ritchielawrence** [comment]
You can filter Cmdow's output with FINDSTR and a regular expression:-

```batch
for /f %%a in ('cmdow /b ^| findstr "explorer.*CRAZY WINDOW NAME"') do (
  cmdow %%a /act
)
```
Note the pipe character (|) has been 'escaped' using a carat (^). Adjust the options in the second use of Cmdow to suit your requirements.
