### ISSUE TITLE
/RUN  /MOV and /SIZ in a single command?

### ISSUE THREAD

**Issue by asinning** [ritchielawrence/cmdow#6]
Not an issue, but a question.  I hope I'm not asking at the wrong place.  I'd like to open a new microsoft-edge window and then set its location and size.  

Trying:
`cmdow.exe /RUN "microsoft-edge:http://www.page.com/location /mov 1000 100 /siz 200 500`
Doesn't seem to do what I'm hoping for.

The best I can find is to launch the program and then move it by its name, but I have to figure out its name.  So it goes.

**Comment by ritchielawrence** [comment]
This batch file launches Microsoft Edge, then moves and resizes the window. The ping command is used to pause execution of the batch file so the window is created before attempts to move or resize it:-

``` batch
echo off
start microsoft-edge:http://google.co.uk
ping -n 2 127.0.0.1
for /f %%a in ('cmdow /f /t ^| findstr ApplicationFrameHost.*Google') do (
  cmdow %%a /mov 1000 100
  cmdow %%a /siz 200 500
)
```
