### ISSUE TITLE
A request - not an issue

### ISSUE THREAD

**Issue by bcosme1** [ritchielawrence/cmdow#8]
Ritchielawrence, amazing tool! Is there a way to get this also uploaded on the SourceForge website? The company I work for does not allow files from Github but allows from SourceForge. I would love to get this approved by the company to begin using it. Used it for personal use and it works miracles.

**Comment by ritchielawrence** [comment]
Thanks for the kind words. Cmdow used to be hosted at SF, but was moved to GH when SF decided it was acceptable to bundle crapware with downloads.
