### ISSUE TITLE
Feature request, FONT and COLOR

### ISSUE THREAD

**Issue by tarvcode** [ritchielawrence/cmdow#9]
Any possibility to add adjustment of font size and color?  Can't seem to find a way to adjust the font size at command line.  Also, the basic COLOR command is pretty color limited.

Anyway, finding this tool pretty handy, thanks!

**Comment by ritchielawrence** [comment]
To change the font, see [How to Customize the Font in Windows Command Prompt](https://www.wikihow.com/Customize-the-Font-in-Windows-Command-Prompt)
To change the colour, see [Ansicon](https://github.com/adoxa/ansicon) or Google [cmd.exe ansi colour](https://www.google.co.uk/search?q=cmd.exe+ansi+colour)
